# Generated by Django 5.0.3 on 2025-10-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_translation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='article_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Article No.'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='In Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product/Service'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='In Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unit'),
        ),
    ]
